"""The deep module: the voter's questions over a local index, with no HTTP and no network.

Public surface: ``Core``, the ``IndexSource`` port and the answer models.
"""

from br_elections_mcp.core.answers import (
    CalendarSourceInfo,
    CandidateAnswer,
    CandidateData,
    CandidateListItem,
    CandidateProfile,
    CandidatesAnswer,
    CandidatesComparisonAnswer,
    CandidatesComparisonData,
    CandidatesData,
    Coalition,
    CoalitionDetail,
    ComparedAssets,
    ComparedCandidate,
    CuratedSource,
    DatasetHealth,
    ElectionInfo,
    ElectionInfoAnswer,
    ElectionInfoData,
    ElectionInfoRound,
    Federation,
    FederationDetail,
    IndexHealth,
    IndexHealthCheckError,
    MissingCandidacy,
    MunicipalitiesAnswer,
    MunicipalitiesData,
    Municipality,
    MunicipalityMatch,
    NotFound,
    Party,
    PollingPlace,
    PollingPlaceAnswer,
    PollingPlaceData,
    PollingPlaceListItem,
    PollingPlacesAnswer,
    PollingPlacesData,
    PreviousPlace,
    RunningMate,
    Source,
)
from br_elections_mcp.core.clock import Clock, system_clock
from br_elections_mcp.core.core import STALE_AFTER_HOURS, Core, Near
from br_elections_mcp.core.errors import IndexUnavailable, InvalidQuery
from br_elections_mcp.core.index_source import IndexSource, IndexSourceUnavailable, IndexVersion

__all__ = [
    "STALE_AFTER_HOURS",
    "CalendarSourceInfo",
    "CandidateAnswer",
    "CandidateData",
    "CandidateListItem",
    "CandidateProfile",
    "CandidatesAnswer",
    "CandidatesComparisonAnswer",
    "CandidatesComparisonData",
    "CandidatesData",
    "Clock",
    "Coalition",
    "CoalitionDetail",
    "ComparedAssets",
    "ComparedCandidate",
    "Core",
    "CuratedSource",
    "DatasetHealth",
    "ElectionInfo",
    "ElectionInfoAnswer",
    "ElectionInfoData",
    "ElectionInfoRound",
    "Federation",
    "FederationDetail",
    "IndexHealth",
    "IndexHealthCheckError",
    "IndexSource",
    "IndexSourceUnavailable",
    "IndexUnavailable",
    "IndexVersion",
    "InvalidQuery",
    "MissingCandidacy",
    "MunicipalitiesAnswer",
    "MunicipalitiesData",
    "Municipality",
    "MunicipalityMatch",
    "Near",
    "NotFound",
    "Party",
    "PollingPlace",
    "PollingPlaceAnswer",
    "PollingPlaceData",
    "PollingPlaceListItem",
    "PollingPlacesAnswer",
    "PollingPlacesData",
    "PreviousPlace",
    "RunningMate",
    "Source",
    "system_clock",
]
